# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-09 18:56
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterPreset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('relief_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ReliefMap')),
            ],
        ),
        migrations.CreateModel(
            name='TemplatePreset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('raw_templates', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='mapitem',
            name='relief_map',
        ),
        migrations.AddField(
            model_name='mapitemtemplate',
            name='relief_map',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.ReliefMap'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filterpreset',
            name='templates',
            field=models.ManyToManyField(to='web.MapItemTemplate'),
        ),
    ]
