# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-17 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reliefmap',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
