# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-27 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_reliefmap_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapItemTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(default='Other', max_length=120)),
                ('sub_category', models.CharField(default='Other', max_length=120)),
            ],
        ),
    ]
