# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-27 17:31
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_mapitemtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('relief_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ReliefMap')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.MapItemTemplate')),
            ],
        ),
    ]
